### ISSUE TITLE
Modular pipelines - Write integration test on a canonical pipeline

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibl-photometry#10]
The photometry pipelines are diverse and highly volatile.
So we already have a way to perform pre-processing in a modular way.

We need to make sure we can refactor and add to it by having a proper integration test.

**Comment by grg2rsr** [comment]
see https://github.com/int-brain-lab/ibl-photometry/commit/b8baa1e46a4a50f6aea045eb5a960f8c95f7b213
