### ISSUE TITLE
inconsistent extraction of data from wittenlab and cortexlab

### ISSUE THREAD

**Issue by grg2rsr** [int-brain-lab/ibl-photometry#35]
Data from Alejandro is extracted differently than data from Carolina

```
from one.api import ONE
one = ONE(base_url='https://alyx.internationalbrainlab.org', mode='remote')

# an example eid from alejandros dataset
eid = one.search(dataset='photometry.signal.pqt', lab='wittenlab')[0]
print(one.load_dataset(eid, 'photometry.signal').columns)

# an example eid from carolines dataset
eid = one.search(dataset='photometry.signal.pqt', lab='cortexlab')[0]
print(one.load_dataset(eid, 'photometry.signal').columns)
```
output:
```
Index(['Region0G', 'Region1G', 'Region2G', 'times', 'wavelength', 'name',
       'color', 'include'],
      dtype='object')
Index(['G0', 'G4', 'times', 'valid', 'wavelength', 'name', 'color'], dtype='object')
```

@oliche do you know about this? Is this caused by the different neurophotometrics roi naming?

**Comment by grg2rsr** [comment]
related to this:
Data from alejandro does not pass the validation schema that was set up for carolinas data
'''
SchemaError: column 'SystemTimestamp' not in dataframe. Columns in dataframe: ['FrameCounter', 'Timestamp', 'LedState', 'Region0G', 'Region1G', 'Region2G']
'''

**Comment by oliche** [comment]
Yes this is due to the change of Neurophotometrics/Bonsai version. 
Both should be supported and validated accordingly !
