### ISSUE TITLE
Define internal data format for photometry

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibl-photometry#7]
We have settled on pynapple.

- [x] a TsdFrame or TsdSeries contains the signal.
- [x] if there is one or several reference channel(s) it is in a different Frame/Series
- [x] if there are several signal bands, the TsdFrame can be an array
- [x] the reference TsdFrame has the same dimensions as the signal frame
- [x] if only one of the signal bands has a meaningful reference, the empty reference is filled with NaNs
- [x] column names should be rois or regions names
- [ ] We need to look into the possibility of attaching a "trace header" metadata dictionary to the Pynapple object.
- [x] Create an integration test passing the synthetic dataset through common pipeline

**Comment by grg2rsr** [comment]
metadata for pynapple is coming soon [(merged PR)](https://github.com/pynapple-org/pynapple/pull/343)

**Comment by grg2rsr** [comment]
@oliche would close this now, documentation of the data format is now part of #28

**Comment by grg2rsr** [comment]
#32 proposal to drop pynapple again and revert to pd.DataFrames
