### ISSUE TITLE
Create low-level photometry io functions 

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ibl-photometry#8]
It needs to be easy and straightforward to convert data sources to the format defined in #7 

It's a good opportunity to try test-driven development.

- [ ] ~~load raw photometry neurophotometrics old format~~
- [x] load raw photometry from Bonsai workflow 6 of neurophotometrics (UCL dataset) - re-use validators from iblrig
- [ ] ~~Doric / generic Csvs from mainenlab~~
- [x] from ibl photometry parquet Alejandro (ie. no isosbestic)
- [x] from ibl photometry parquet UCL (ie. with isosbestic)
- [x] cast from numpy arrays
- [x] cast from generic Dataframe

Add some examples for users

**Comment by grg2rsr** [comment]
I added a dedicated [.io](https://github.com/int-brain-lab/ibl-photometry/blob/fddd5562aae3bb2114b61cbcbc35ccd27e292632/src/iblphotometry/io.py#L13) module for the readers. To discuss here: When reading in a file, we will after what is discussed in #7 end up with several `TsdFrames`, one for each band. Currently I put them into a dict, with the keys being the name of the bands, but this is up for discussion.

**Comment by grg2rsr** [comment]
also, I came back to the question on how to deal with `eid` and `pid`. The class `PhotometryLoader` should support both, and if fibers are probes, a query by `pid` should return data that is associated to that fiber. Question here is again the return type. If queried with an `eid`, it would currently return a `dict` of `TsdFrames` (up for discussion). If queried with a `pid`, what should be the return type?
- a `dict` of `Tsd`: this would be consistent
- a `TsdFrame` with the columns `signal` and `reference`. This would be convenient for analysis, but no really consistent with the behavior when a eid is passed.

**Comment by oliche** [comment]
> I added a dedicated [.io](https://github.com/int-brain-lab/ibl-photometry/blob/fddd5562aae3bb2114b61cbcbc35ccd27e292632/src/iblphotometry/io.py#L13) module for the readers. To discuss here: When reading in a file, we will after what is discussed in https://github.com/int-brain-lab/ibl-photometry/issues/7 end up with several TsdFrames, one for each band. Currently I put them into a dict, with the keys being the name of the bands, but this is up for discussion.

Yes all fine here, the good thing with pynapple is that we can address the table easily by index: `tsd_frame_signal[:, 0]` for example


> also, I came back to the question on how to deal with eid and pid. The class PhotometryLoader should support both, and if fibers are probes, a query by pid should return data that is associated to that fiber. Question here is again the return type. If queried with an eid, it would currently return a dict of TsdFrames (up for discussion). If queried with a pid, what should be the return type?
> 
>     a dict of Tsd: this would be consistent
>     a TsdFrame with the columns signal and reference. This would be convenient for analysis, but no really consistent with the behavior when a eid is passed.
> 

Again the first purpose of this issue is to finalize and merge the simple file loaders before looking at IBL loaders. If you really want to start, the `PhotometryLoader` should inherit from `brainbox.io.SessionLoader` in the same manner as this one https://github.com/int-brain-lab/ibllib/blob/3224aed976372b87f049a98c06474d733ab583c7/brainbox/io/one.py#L1639 . But I think we should first merge the low level functions !

**Comment by grg2rsr** [comment]
#24

**Comment by grg2rsr** [comment]
marked as completed as we will likely never care about the missing data formats
